name = "angle_and_force_normal_new"
stan_file = "src/stan/angle_and_force_normal.stan"
data_dir = "data/prepared/new"
modes = ["prior", "posterior", "cross_validation"]

[sample_kwargs]
show_progress = true
save_warmup = false
iter_warmup = 1000
iter_sampling = 1000

[sample_kwargs.cross_validation]
chains = 1
